[package]
edition = "2021"
name = "senedteheven"
version = "0.6.0"

[dependencies]
bevy = { version = "0.15", default-features = true }
bevy_ecs_tilemap = { version = "0.15", default-features = true }
tiled = { version = "0.14", features = ["world"] }